apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: terragrunt-variant-apps
  annotations:
    github.com/project-slug: variant-inc/terragrunt-variant-apps
    backstage.io/techdocs-ref: dir:.
spec:
  type: other
  lifecycle: production
  owner: cloud-ops
