# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "engineering-tf-state20210118220815943200000002"
    encrypt = true
    key     = "space/project-group/project-name/./terraform.tfstate"
    region  = "us-east-1"
  }
}
