---
name: Publish Tool

on:
  push:

jobs:
  branch-build:
    name: Branch Build
    runs-on: [ops]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup
        id: setup
        uses: variant-inc/actions-setup@v1
      - name: Package
        shell: pwsh
        run: |
          New-Item -ItemType Directory pack
          Move-Item -Path ./deploy -Destination ./pack
          Move-Item -Path ./modules -Destination ./pack
          ./.variant/deploy/push_package.ps1 `
            -PackageName ${{ github.event.repository.name }} `
            -Version ${{ steps.setup.outputs.image_version }} `
            -BasePackagePath ./pack `
            -Spaces DataScience