---
name: Pre Commit

on:
  push:

jobs:
  pre-commit:
    name: Pre Commit
    runs-on: [eks]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Pre-Commit Dependencies
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          curl -fsSL "$(curl -s https://api.github.com/repos/gruntwork-io/terragrunt/releases/latest | grep -o -E -m 1 "https://.+?_linux_amd64")" > terragrunt
          chmod +x terragrunt
          terragrunt --version

      - name: Pre-commit
        run: |
          tflint --init
          pre-commit install
          pre-commit run --color=always --show-diff-on-failure --all-files
