---
name: Pre Commit

on:
  push:

jobs:
  pre-commit:
    name: Pre Commit
    runs-on: [eks]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Pre-commit
        run: |
          tflint --init
          pre-commit run --color=always --show-diff-on-failure --all-files
